### ISSUE TITLE
Integration Tests Failing

### ISSUE THREAD

**Issue by martinjoconnor** [protegeproject/mapping-master-integration-tests#1]
I updated the integration test POM to point to the current MM development iteration (1.4-SNAPSHOT) and about a dozen tests are now failing.

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.mm.renderer.owlapi.OWLAPIRendererIT
Tests run: 122, Failures: 2, Errors: 6, Skipped: 0, Time elapsed: 3.695 sec <<< FAILURE!
Running org.mm.renderer.text.TextRendererIT
Tests run: 103, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 0.198 sec <<< FAILURE!

Results :

Failed tests: 
  TestOutOfRangeColumnInReference(org.mm.renderer.owlapi.OWLAPIRendererIT)
  TestOutOfRangeRowInReference(org.mm.renderer.owlapi.OWLAPIRendererIT)
  TestOutOfRangeColumnInReference(org.mm.renderer.text.TextRendererIT)
  TestErrorIfEmptyRDFIDDirectiveInReference(org.mm.renderer.text.TextRendererIT)
  TestOutOfRangeRowInReference(org.mm.renderer.text.TextRendererIT)

Tests in error: 
  TestIndividualDeclarationWithMultipleSameIndividual(org.mm.renderer.owlapi.OWLAPIRendererIT)
  TestSkipIfEmptyLiteralInReference(org.mm.renderer.owlapi.OWLAPIRendererIT)
  TestSkipIfEmptyLocationInReference(org.mm.renderer.owlapi.OWLAPIRendererIT)
  TestIndividualDeclarationWithDifferentIndividuals(org.mm.renderer.owlapi.OWLAPIRendererIT)
  TestIndividualDeclarationWithMultipleDifferentIndividuals(org.mm.renderer.owlapi.OWLAPIRendererIT)
  TestIndividualDeclarationWithSameIndividual(org.mm.renderer.owlapi.OWLAPIRendererIT)

Tests run: 225, Failures: 5, Errors: 6, Skipped: 0

**Comment by martinjoconnor** [comment]
I fixed the errors in the tests but there are still some failures, which mostly seem to relate to range checking - or lack thereof:

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.mm.renderer.owlapi.OWLAPIRendererIT
Tests run: 122, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 3.749 sec <<< FAILURE!
Running org.mm.renderer.text.TextRendererIT
Tests run: 103, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 0.208 sec <<< FAILURE!

Results :

Failed tests: 
  TestOutOfRangeColumnInReference(org.mm.renderer.owlapi.OWLAPIRendererIT)
  TestSkipIfEmptyLiteralInReference(org.mm.renderer.owlapi.OWLAPIRendererIT)
  TestOutOfRangeRowInReference(org.mm.renderer.owlapi.OWLAPIRendererIT)
  TestOutOfRangeColumnInReference(org.mm.renderer.text.TextRendererIT)
  TestErrorIfEmptyRDFIDDirectiveInReference(org.mm.renderer.text.TextRendererIT)
  TestOutOfRangeRowInReference(org.mm.renderer.text.TextRendererIT)

Tests run: 225, Failures: 6, Errors: 0, Skipped: 0

**Comment by johardi** [comment]
All the tests should be green now
